### ISSUE TITLE
Slim skin support

### ISSUE THREAD

**Issue by Lualttt** [raketenben/statue-generator#1]
Please add slim skin support this would really improve the generator (it's already perfect put this would just add that little extra). Anyways love the gen very nice!

**Comment by raketenben** [comment]
Yeah, I probably should add it. But I can't make the statue itself any smaller, the best I can do is stretch the arms of the slim skin to the same size as the Steve skin.

**Comment by raketenben** [comment]
Support for Slim Skins added in the latest commit [#68ee5e](https://github.com/raketenben/statue-generator/commit/68ee5ee637bcad4294ff6c47c931d59b5163f95b)
